apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    run: ftps-service
spec:
  type: NodePort #LoadBalancer
  selector:
    run: ftps-service
  ports:
  - port: 21
    targetPort: 21
    nodePort : 21
    name: ftps-service
  - port: 21000
    targetPort : 21000
    nodePort : 21000
    name : my-ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      run: ftps-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps-deployment
    spec:
      containers:
      - name: ftps-deployment
        image: ftps_img
        imagePullPolicy: Never
