apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  #loadBalancerIP: 192.168.99.101
  type: LoadBalancer
  selector:
    run: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 21000
    targetPort : 21000
    name : my-ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      run: ftps
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
