apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    run: grafana
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_img
        imagePullPolicy: Never
        env:
        - name: GRAF_USER
          valueFrom:
            secretKeyRef:
              name: jdussert
              key: user
        - name: GRAF_PASS
          valueFrom:
            secretKeyRef:
              name: jdussert
              key: password
        ports:
        - containerPort: 3000
